'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

'''

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        self.s = s
        self.t = t
        self.result = []

        if len(self.t) == len(self.s) + 1 and len(self.s) <= 1000:
            for el in self.t:
                if el not in self.s:
                    self.result.append(el)
                    return ''.join(self.result)
                elif el in self.s and t.count(el) > s.count(el):
                    return el
